### ISSUE TITLE
turn off the monitor and then turn it back on, Alt+Tab stops working

### ISSUE THREAD

**Issue by safasfk** [H3rmt/hyprswitch#350]
ENV
hyprshell 4.7.1 in release mode on hyprland 0.51.1
gtk4-layer-shell-1.2.0-1.el10.x86_64

 config
cat .config/hyprshell/config.ron
(
version: 3,
windows: (
scale: 8.5,
items_per_row: 5,
switch: (
modifier: "alt",
filter_by: [],
switch_workspaces: false,
),
),
)
how to run
`exec-once = hyprshell run &`

I have two computers and one monitor, and I use a KVM switch to toggle between the two. I noticed that when I switch from the Windows computer to the Hyprland computer, HyprShell stops working—only the keyboard shortcuts（ALT-TAB） don’t work, but the process is still running."
here is part of log

11.090649419s TRACE event_handler:close_switch: Restored previous follow_mouse value: 0
  11.091048216s TRACE event_handler:close_switch: Hiding window (windows) 1
  11.091211838s DEBUG event_handler:close_switch: Switching to client hyprshell stops working properly if I accidentically try to alt tab while being in a scratchpad aka special workspaces. · Issue #311 · H3rmt/hyprshell - Google Chrome
  11.091228474s TRACE event_handler: handling event: CloseSwitch
  11.091233359s DEBUG event_handler: Switch is already closed
  11.091305425s TRACE event_handler: execute switch to client: 0x55ec2f220ce0
  15.277440732s DEBUG event_handler: Received restart request (monitor added), starting debounce timer
  15.375427185s DEBUG event_handler: Received restart request (monitor removed), starting debounce timer
  15.375439816s TRACE event_handler: Cancelled previous debounce timer
  16.877805762s TRACE event_handler: Debounce timer expired, triggering restart (monitor removed)
  16.877880833s  INFO event_handler: Restarting gui (monitor removed)
  16.877918183s TRACE event_handler: handling event: Restart
  16.882322872s TRACE event_handler:stop_switch: Restored previous follow_mouse value: 0
  16.882339299s TRACE event_handler:stop_switch: Closing window 1
  28.439823891s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  29.116702846s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  29.446749529s DEBUG socket_handler:handle_client: Received command: CloseSwitch
  30.331809481s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  30.552688532s DEBUG socket_handler:handle_client: Received command: CloseSwitch

**Comment by H3rmt** [comment]
Do you see any new logs after trying to open the switch window or the overview?

**Comment by safasfk** [comment]
hyprshell run -vv       
   0.000095685s DEBUG FEATURES: JSON5 support: true, Config command: true, Debug command: true, Launcher calc: true
   0.000118535s DEBUG ENV: HYPRSHELL_NO_LISTENERS: -None-, HYPRSHELL_NO_ALL_ICONS: -None-, HYPRSHELL_RELOAD_TIMEOUT: -None-, HYPRSHELL_LOG_MODULE_PATH: -None-, HYPRSHELL_NO_USE_PLUGIN: -None-, HYPRSHELL_EXPERIMENTAL: -None-, HYPRSHELL_RUN_ACTIONS_IN_DEBUG: -None-
   0.000144604s DEBUG OS: linux, ARCH: x86_64, NAME="Rocky Linux"
   0.000163848s DEBUG Checking if daemon is running on /run/user/1000/hypr/71a1216abcc7031776630a6d88f105605c4dc1c9_1760443787_1749233908/hyprshell.sock
   0.000521161s TRACE hyprland Version { branch: "", commit: "71a1216abcc7031776630a6d88f105605c4dc1c9", version: Some("0.51.1"), dirty: false, commit_message: "[gha] Nix: update inputs", commit_date: "Mon Sep 22 20:54:03 2025", tag: "v0.51.1", commits: "6436", build_aquamarine: "0.9.4", flags: [] }
   0.000577265s  INFO Starting hyprshell 4.7.1 in release mode on hyprland 0.51.1
   0.000634829s TRACE Found config file at "/home/zosy/.config/hyprshell/config.ron"
   0.098713921s  INFO preactivate: Using theme: Some("Adwaita") and icon theme: Some("Adwaita"), please make sure both exist, else weird icon or graphical issues may occur
   0.103177588s TRACE preactivate: Icon theme search path: ["/home/zosy/.local/share/icons", "/home/zosy/.icons", "/home/zosy/.local/share/flatpak/exports/share/icons", "/var/lib/flatpak/exports/share/icons", "/usr/share/icons", "/usr/share/pixmaps"]
   0.103198730s DEBUG preactivate:reload_icons: found 304 icons from theme
   0.103445738s DEBUG preactivate:reload_icons: found 0 icons from filesystem in "/home/zosy/.local/share/icons" paths (in background)
   0.103592709s TRACE preactivate:reload_icons: icon map filled
   0.103822651s DEBUG preactivate:reload_icons: found 24 icons from filesystem in "/usr/share/pixmaps" paths (in background)
   0.104157306s DEBUG preactivate:reload_icons: found 1 icons from filesystem in "/var/lib/flatpak/exports/share/icons" paths (in background)
   0.104183039s DEBUG preactivate:reload_icons: found 5 icons from filesystem in "/home/zosy/.local/share/flatpak/exports/share/icons" paths (in background)
   0.104340564s TRACE preactivate:reload_files: found 104 desktop files
   0.106511388s TRACE preactivate:reload_files: Collected all desktop files
   0.107201413s TRACE preactivate:reload_files: found 4 mimeapps lists
   0.107578137s TRACE preactivate:reload_files: Collected all mime files
   0.107842619s TRACE preactivate:reload_class_to_icon_map: filled class to icon map
   0.108003562s TRACE preactivate:reload_desktop_entries_map: filled launcher desktop file map
   0.108011182s DEBUG preactivate: Reloaded desktop data in 4.408969ms
   0.108017899s DEBUG Reloading hyprland config
   0.114622190s DEBUG preactivate:reload_icons: found 1441 icons from filesystem in "/home/zosy/.icons" paths (in background)
   0.254447842s  INFO Starting gui loop
   0.254677819s DEBUG Application created
   0.254700320s  INFO socket_handler: Starting socket on "/run/user/1000/hypr/71a1216abcc7031776630a6d88f105605c4dc1c9_1760443787_1749233908/hyprshell.sock"
   0.261700421s DEBUG activate: Loading custom css file "/home/zosy/.config/hyprshell/styles.css"
   0.303742221s TRACE activate: Storing previous follow_mouse value: 0
   0.303867480s TRACE activate: Cached version: Version { major: 4, minor: 7, patch: 1 }, current version: Version { major: 4, minor: 7, patch: 1 }: Equal
   0.304091011s DEBUG activate: Hyprshell is up to date
   0.304217024s TRACE activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: No migration needed
   0.304253685s DEBUG activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: Loaded config
   0.304330231s TRACE activate:create_binds:load_plugin: plugins: []
   0.304375578s TRACE activate:create_binds:load_plugin:generate: extracting plugin from zip
   0.304717199s TRACE activate:create_binds:load_plugin:generate: extracted 5 files
   0.304726007s TRACE activate:create_binds:load_plugin:generate: configuring defs file
   0.304869131s TRACE activate:create_binds:load_plugin:generate: building plugin
   0.304880684s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpFh2G8Qhyprshell-hyprland-plugin"}: PATH: Some("/usr/share/Modules/bin:/home/zosy/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/zosy/.android-studio/Android/Sdk/platform-tools/:/home/zosy/.local/bin/:/home/zosy/.cargo/bin:/opt/bin:/sbin:/opt/wine/bin")
   0.304892873s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpFh2G8Qhyprshell-hyprland-plugin"}: CPATH: None
   0.304900774s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpFh2G8Qhyprshell-hyprland-plugin"}: Running build command: cd "/tmp/.tmpFh2G8Qhyprshell-hyprland-plugin" && "gcc" "-shared" "-fPIC" "--no-gnu-unique" "-std=c++2b" "-I/usr/include/pixman-1" "-O2" "-o" "/tmp/hyprshell.so" "all.cpp"
   0.306744913s DEBUG preactivate:reload_icons: found 7738 icons from filesystem in "/usr/share/icons" paths (in background)
   2.821079820s TRACE activate:create_binds:load_plugin: generated plugin at "/tmp/hyprshell.so"
   2.821613741s TRACE activate:create_binds:load_plugin: loaded plugin
   3.011954157s TRACE activate:create_binds: layerrules applied
   3.011979722s DEBUG activate: Windows overview disabled
   3.293942088s DEBUG activate:create_windows_switch_window: Created switch window (1)
   3.294662478s  INFO activate: Application initialized
   3.294811501s  INFO Starting hyprshell config reload listener
   3.294975643s  INFO Starting hyprshell css reload listener
   3.295147572s  INFO event_handler: Starting monitor added/removed listener
  11.623014065s DEBUG event_handler: Received restart request (monitor added), starting debounce timer
  11.712437850s DEBUG event_handler: Received restart request (monitor removed), starting debounce timer
  11.712453750s TRACE event_handler: Cancelled previous debounce timer
  13.214552226s TRACE event_handler: Debounce timer expired, triggering restart (monitor removed)
  13.214610320s  INFO event_handler: Restarting gui (monitor removed)
  13.214653637s TRACE event_handler: handling event: Restart
  13.219113371s TRACE event_handler:stop_switch: Restored previous follow_mouse value: 0
  13.219129094s TRACE event_handler:stop_switch: Closing window 1
  13.224229095s  INFO Application exited, restarting
  13.226868670s DEBUG Application exited with code ExitCode(0)
  13.226975977s DEBUG Application created
  13.234858378s DEBUG activate: Loading custom css file "/home/zosy/.config/hyprshell/styles.css"
  13.235136758s TRACE activate: Storing previous follow_mouse value: 0
  13.235190088s TRACE activate: Cached version: Version { major: 4, minor: 7, patch: 1 }, current version: Version { major: 4, minor: 7, patch: 1 }: Equal
  13.235391038s DEBUG activate: Hyprshell is up to date
  13.235515838s TRACE activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: No migration needed
  13.235550814s DEBUG activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: Loaded config
  13.235653038s TRACE activate:create_binds:load_plugin: plugins: [Plugin { name: "hyprshell-hyprland-plugin", author: "h3rmt", handle: "5645ce344390", version: "4.7.1", description: "Plugin for hyprland, used to monitor keypresses - XKB_KEY_Alt||" }]
  13.235671155s DEBUG activate:create_binds:load_plugin: plugin already loaded, skipping
  13.237203971s TRACE activate:create_binds: layerrules applied
  13.237212858s DEBUG activate: Windows overview disabled
  13.248753324s DEBUG activate:create_windows_switch_window: Created switch window (1)
  13.248966583s ERROR activate: Failed to create windows: failed to create overview window

Caused by:
    expected value at line 1 column 1
  13.249191981s DEBUG activate: Starting hyprshell config reload blocker
  34.244049067s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  34.645916584s DEBUG socket_handler:handle_client: Received command: CloseSwitch
  35.222927218s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  35.711942877s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  36.250988739s DEBUG socket_handler:handle_client: Received command: CloseSwitch

**Comment by H3rmt** [comment]
this fails because it cant get the current `client/workspace/monitor`.

It might be possible that there is no workspace active?

**Comment by H3rmt** [comment]
I noticed that get_initial_active also errors if no client is found (even though not having selected a client is allowed).

I think `4.7.2` should resolve the issue

**Comment by safasfk** [comment]
thanks for updating, but seem's still not working, here  is log, if you need more info, let know.

~/Downloads/hyprshell-4.7.2/target/release ./hyprshell run -vv
   0.000062859s DEBUG FEATURES: JSON5 support: true, Config command: true, Debug command: true, Launcher calc: true
   0.000080800s DEBUG ENV: HYPRSHELL_NO_LISTENERS: -None-, HYPRSHELL_NO_ALL_ICONS: -None-, HYPRSHELL_RELOAD_TIMEOUT: -None-, HYPRSHELL_LOG_MODULE_PATH: -None-, HYPRSHELL_NO_USE_PLUGIN: -None-, HYPRSHELL_EXPERIMENTAL: -None-, HYPRSHELL_RUN_ACTIONS_IN_DEBUG: -None-
   0.000103311s DEBUG OS: linux, ARCH: x86_64, NAME="Rocky Linux"
   0.000129282s DEBUG Checking if daemon is running on /run/user/1000/hypr/71a1216abcc7031776630a6d88f105605c4dc1c9_1760508284_1935297729/hyprshell.sock
   0.000399854s TRACE hyprland Version { branch: "", commit: "71a1216abcc7031776630a6d88f105605c4dc1c9", version: Some("0.51.1"), dirty: false, commit_message: "[gha] Nix: update inputs", commit_date: "Mon Sep 22 20:54:03 2025", tag: "v0.51.1", commits: "6436", build_aquamarine: "0.9.4", flags: [] }
   0.000447137s  INFO Starting hyprshell 4.7.2 in release mode on hyprland 0.51.1
   0.000498027s TRACE Found config file at "/home/zosy/.config/hyprshell/config.ron"
   0.086643476s  INFO preactivate: Using theme: Some("Adwaita") and icon theme: Some("Adwaita"), please make sure both exist, else weird icon or graphical issues may occur
   0.090924222s TRACE preactivate: Icon theme search path: ["/home/zosy/.local/share/icons", "/home/zosy/.icons", "/home/zosy/.local/share/flatpak/exports/share/icons", "/var/lib/flatpak/exports/share/icons", "/usr/share/icons", "/usr/share/pixmaps"]
   0.090945003s DEBUG preactivate:reload_icons: found 304 icons from theme
   0.091266842s DEBUG preactivate:reload_icons: found 0 icons from filesystem in "/home/zosy/.local/share/icons" paths (in background)
   0.091433504s TRACE preactivate:reload_icons: icon map filled
   0.091798215s DEBUG preactivate:reload_icons: found 24 icons from filesystem in "/usr/share/pixmaps" paths (in background)
   0.092047228s DEBUG preactivate:reload_icons: found 1 icons from filesystem in "/var/lib/flatpak/exports/share/icons" paths (in background)
   0.092046040s DEBUG preactivate:reload_icons: found 5 icons from filesystem in "/home/zosy/.local/share/flatpak/exports/share/icons" paths (in background)
   0.092107306s TRACE preactivate:reload_files: found 104 desktop files
   0.094310360s TRACE preactivate:reload_files: Collected all desktop files
   0.094899716s TRACE preactivate:reload_files: found 4 mimeapps lists
   0.095360149s TRACE preactivate:reload_files: Collected all mime files
   0.095591272s TRACE preactivate:reload_class_to_icon_map: filled class to icon map
   0.095733808s TRACE preactivate:reload_desktop_entries_map: filled launcher desktop file map
   0.095744358s DEBUG preactivate: Reloaded desktop data in 4.301029ms
   0.095751087s DEBUG Reloading hyprland config
   0.102091947s DEBUG preactivate:reload_icons: found 1441 icons from filesystem in "/home/zosy/.icons" paths (in background)
   0.264717760s  INFO Starting gui loop
   0.264931741s DEBUG Application created
   0.264951993s  INFO socket_handler: Starting socket on "/run/user/1000/hypr/71a1216abcc7031776630a6d88f105605c4dc1c9_1760508284_1935297729/hyprshell.sock"
   0.272197115s DEBUG activate: Loading custom css file "/home/zosy/.config/hyprshell/styles.css"
   0.272509181s TRACE activate: Storing previous follow_mouse value: 0
   0.272551518s TRACE activate: Cached version: Version { major: 4, minor: 7, patch: 2 }, current version: Version { major: 4, minor: 7, patch: 2 }: Equal
   0.272718117s DEBUG activate: Hyprshell is up to date
   0.272804231s TRACE activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: No migration needed
   0.272837194s DEBUG activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: Loaded config
   0.272939601s TRACE activate:create_binds:load_plugin: plugins: []
   0.272986443s TRACE activate:create_binds:load_plugin:generate: extracting plugin from zip
   0.273341268s TRACE activate:create_binds:load_plugin:generate: extracted 5 files
   0.273350137s TRACE activate:create_binds:load_plugin:generate: configuring defs file
   0.273486829s TRACE activate:create_binds:load_plugin:generate: building plugin
   0.273497338s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmph7wyw1hyprshell-hyprland-plugin"}: PATH: Some("/usr/share/Modules/bin:/home/zosy/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/zosy/.android-studio/Android/Sdk/platform-tools/:/home/zosy/.local/bin/:/home/zosy/.cargo/bin:/opt/bin:/sbin:/opt/wine/bin")
   0.273508005s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmph7wyw1hyprshell-hyprland-plugin"}: CPATH: None
   0.273514988s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmph7wyw1hyprshell-hyprland-plugin"}: Running build command: cd "/tmp/.tmph7wyw1hyprshell-hyprland-plugin" && "gcc" "-shared" "-fPIC" "--no-gnu-unique" "-std=c++2b" "-I/usr/include/pixman-1" "-O2" "-o" "/tmp/hyprshell.so" "all.cpp"
   0.316592903s DEBUG preactivate:reload_icons: found 7738 icons from filesystem in "/usr/share/icons" paths (in background)
   2.745115088s TRACE activate:create_binds:load_plugin: generated plugin at "/tmp/hyprshell.so"
   2.745741579s TRACE activate:create_binds:load_plugin: loaded plugin
   2.898011111s TRACE activate:create_binds: layerrules applied
   2.898028552s DEBUG activate: Windows overview disabled
   3.128151614s DEBUG activate:create_windows_switch_window: Created switch window (1)
   3.129103210s  INFO activate: Application initialized
   3.129252376s  INFO Starting hyprshell config reload listener
   3.129428942s  INFO Starting hyprshell css reload listener
   3.129581138s  INFO event_handler: Starting monitor added/removed listener
   7.459445963s DEBUG event_handler: Received restart request (monitor added), starting debounce timer
   7.547360087s DEBUG event_handler: Received restart request (monitor removed), starting debounce timer
   7.547378725s TRACE event_handler: Cancelled previous debounce timer
   9.049628219s TRACE event_handler: Debounce timer expired, triggering restart (monitor removed)
   9.049694585s  INFO event_handler: Restarting gui (monitor removed)
   9.049758619s TRACE event_handler: handling event: Restart
   9.054151919s TRACE event_handler:stop_switch: Restored previous follow_mouse value: 0
   9.054171968s TRACE event_handler:stop_switch: Closing window 1
   9.059084807s  INFO Application exited, restarting
   9.059627985s DEBUG Application exited with code ExitCode(0)
   9.059720353s DEBUG Application created
   9.067833302s DEBUG activate: Loading custom css file "/home/zosy/.config/hyprshell/styles.css"
   9.068137030s TRACE activate: Storing previous follow_mouse value: 0
   9.068194153s TRACE activate: Cached version: Version { major: 4, minor: 7, patch: 2 }, current version: Version { major: 4, minor: 7, patch: 2 }: Equal
   9.068357683s DEBUG activate: Hyprshell is up to date
   9.068451908s TRACE activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: No migration needed
   9.068491268s DEBUG activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: Loaded config
   9.068599210s TRACE activate:create_binds:load_plugin: plugins: [Plugin { name: "hyprshell-hyprland-plugin", author: "h3rmt", handle: "560cee438bc0", version: "4.7.2", description: "Plugin for hyprland, used to monitor keypresses - XKB_KEY_Alt||" }]
   9.068617617s DEBUG activate:create_binds:load_plugin: plugin already loaded, skipping
   9.070299577s TRACE activate:create_binds: layerrules applied
   9.070310548s DEBUG activate: Windows overview disabled
   9.081284153s DEBUG activate:create_windows_switch_window: Created switch window (1)
   9.081506168s ERROR activate: Failed to create windows: failed to create switch window

Caused by:
    0: unable to get initial active data
    1: unable to get initial workspace
    2: expected value at line 1 column 1
   9.081755124s DEBUG activate: Starting hyprshell config reload blocker

**Comment by H3rmt** [comment]
Ok it really looks like there is no active workspace on the monitor

**Comment by H3rmt** [comment]
you you run `hyprctl monitors -j` exactly when turning the monitor on?

like use `sleep 5; hyprctl monitors -j`. 

Please also try the same with `hyprctl activewindow -j` and `hyprctl activeworkspace -j`

Hyprshell asumes that every monitor has an active workspace at all times (which should be case?).

**Comment by safasfk** [comment]
Not sure if this helps — let me know if you need any more tests.

hyprctl activewindow -j
{
    "address": "0x557d96319830",
    "mapped": true,
    "hidden": false,
    "at": [965, 5],
    "size": [950, 1029],
    "workspace": {
        "id": 1,
        "name": "1"
    },
    "floating": false,
    "pseudo": false,
    "monitor": 0,
    "class": "org.kde.konsole",
    "title": "zosy@xishuokeji:~ — Konsole",
    "initialClass": "org.kde.konsole",
    "initialTitle": "Profile 1 — Konsole",
    "pid": 49861,
    "xwayland": false,
    "pinned": false,
    "fullscreen": 0,
    "fullscreenClient": 0,
    "grouped": [],
    "tags": [],
    "swallowing": "0x0",
    "focusHistoryID": 0,
    "inhibitingIdle": false,
    "xdgTag": "",
    "xdgDescription": ""
}
➜  ~ hyprctl activeworkspace -j
{
    "id": 1,
    "name": "1",
    "monitor": "DP-2",
    "monitorID": 0,
    "windows": 2,
    "hasfullscreen": false,
    "lastwindow": "0x557d96319830",
    "lastwindowtitle": "zosy@xishuokeji:~ — Konsole",
    "ispersistent": false
}
➜  ~ hyprctl monitors -j       
[{
    "id": 0,
    "name": "DP-2",
    "description": "Dell Inc. DELL U2720QM 369RW13",
    "make": "Dell Inc.",
    "model": "DELL U2720QM",
    "serial": "369RW13",
    "width": 3840,
    "height": 2160,
    "physicalWidth": 600,
    "physicalHeight": 340,
    "refreshRate": 59.99700,
    "x": 0,
    "y": 0,
    "activeWorkspace": {
        "id": 1,
        "name": "1"
    },
    "specialWorkspace": {
        "id": 0,
        "name": ""
    },
    "reserved": [0, 0, 0, 41],
    "scale": 2.00,
    "transform": 0,
    "focused": true,
    "dpmsStatus": true,
    "vrr": false,
    "solitary": "0",
    "solitaryBlockedBy": ["WINDOWED","CANDIDATE"],
    "activelyTearing": false,
    "tearingBlockedBy": ["NOT_TORN","USER","CANDIDATE"],
    "directScanoutTo": "0",
    "directScanoutBlockedBy": ["USER","CANDIDATE"],
    "disabled": false,
    "currentFormat": "XRGB8888",
    "mirrorOf": "none",
    "availableModes": ["3840x2160@60.00Hz","3840x2160@29.56Hz","2560x1440@59.95Hz","2048x1280@59.92Hz","2048x1152@60.00Hz","1920x1200@59.88Hz","1920x1080@60.00Hz","1920x1080@59.94Hz","1920x1080@50.00Hz","1920x1080@23.98Hz","1600x1200@60.00Hz","1680x1050@59.95Hz","1280x1024@75.03Hz","1280x1024@60.02Hz","1280x800@59.81Hz","1152x864@75.00Hz","1280x720@59.94Hz","1280x720@50.00Hz","1024x768@75.03Hz","1024x768@60.00Hz","800x600@75.00Hz","800x600@60.32Hz","720x576@50.00Hz","720x480@59.94Hz","640x480@75.00Hz","640x480@59.94Hz","640x480@59.93Hz"]
}]

**Comment by xskj4** [comment]
I'm not very familiar with programming, but I temporarily solved the problem with the help of AI. My approach is to wait for Wayland/Hyprland to be ready after turning the monitor back on before performing the corresponding actions.you can optimize it to make the implementation more reasonable and elegant.
[+]~/Desktop/hyprshell/crates/windows-lib/src/switch git:(hyprshell-release) ✗ cat fix.patch[/+]
```[-] ~/Desktop/hyprshell/crates/windows-lib/src/switch git:(hyprshell-release) ✗ cat fix.patch[/-]
--- create-orig.rs 2025-10-21 20:43:25.725875047 +0800
+++ create.rs 2025-10-21 20:42:48.607711499 +0800
@@ -15,6 +15,8 @@
use gtk4_layer_shell::{KeyboardMode, Layer, LayerShell};
use std::collections::HashMap;
use tracing::{debug, debug_span};
+use std::thread;
+use std::time::Duration;
pub fn create_windows_switch_window(
app: &Application,
@@ -64,6 +66,18 @@
window.set_visible(false);
debug!("Created switch window ({})", window.id());
+ // Ensure hyprland is ready before attempting to get initial active data.
+ // If not ready, log and wait until it becomes ready to avoid transient errors
+ // (for example when a monitor was just turned on).
+ let active = loop {
+ match get_initial_active() {
+ Ok(a) => break a,
+ Err(e) => {
+ debug!("waiting for wayland/hyprland ready: {e}");
+ thread::sleep(Duration::from_millis(100));
+ }
+ }
+ };
Ok(WindowsSwitchData {
config: WindowsSwitchConfig {
@@ -78,7 +92,8 @@
main_flow: clients_flow,
workspaces: HashMap::default(),
clients: HashMap::default(),
- active: get_initial_active().context("unable to get initial active data")?,
+ // active: get_initial_active().context("unable to get initial active data")?,
+ active,
hypr_data: HyprlandData::default(),
})
}
```

**Comment by xskj4** [comment]
The solution above took 2 days and only fixed the issue of Alt+Tab not showing, but I discovered a second problem. Sometimes, after reopening the display, it doesn't stay on the current workspace. For example, when I close the display while on workspace 1, reopening it sometimes causes it to jump to workspace 6. My Hyprland setup has 5 workspaces: 1, 2, 3, 4, and 5. This issue persists whenever I restart the display.

**Comment by H3rmt** [comment]
> The solution above took 2 days and only fixed the issue of Alt+Tab not showing, but I discovered a second problem. Sometimes, after reopening the display, it doesn't stay on the current workspace. For example, when I close the display while on workspace 1, reopening it sometimes causes it to jump to workspace 6. My Hyprland setup has 5 workspaces: 1, 2, 3, 4, and 5. This issue persists whenever I restart the display.

I cant relay explain why this is happening, placing the window on the current workspace is done by gtk and hyprland.

I will implement a solution that doesnt crash hyprshell if no connected workspace is being found

**Comment by H3rmt** [comment]
I added the workaround that sleeps if no workspace is selected, it retries for 5 seconds and only fails if no workspace was retuned as primary during that time

**Comment by xskj4** [comment]
4.8.0 didn’t fix this issue — instead, after logging in, it now takes about 5 seconds for Hyprshell to start working. Please consider my patch; I’ve found that sometimes the “workspace 6” problem isn’t actually caused by Hyprshell, It’s possible that this is actually a Hyprland bug. so my patch completely solves this issue. i used it over weeks, works fine.
4.8.0 log
```hyprshell run -vv
   0.000022118s DEBUG FEATURES: json5_config: true, generate_config_command: true, debug_command: true, launcher_calc: true, clipboard_compress_lz4: true, clipboard_compress_zstd: true, clipboard_compress_brotli: true, clipboard_encrypt_chacha20poly1305: true, clipboard_encrypt_aes_gcm: true
   0.000048550s DEBUG ENV: HYPRSHELL_NO_LISTENERS: -None-, HYPRSHELL_NO_ALL_ICONS: -None-, HYPRSHELL_RELOAD_TIMEOUT: -None-, HYPRSHELL_LOG_MODULE_PATH: -None-, HYPRSHELL_NO_USE_PLUGIN: -None-, HYPRSHELL_EXPERIMENTAL: -None-, HYPRSHELL_RUN_ACTIONS_IN_DEBUG: -None-
   0.000073607s DEBUG OS: linux, ARCH: x86_64, NAME="Rocky Linux"
   0.000111045s DEBUG Checking if daemon is running on /run/user/1000/hypr/06b37c390715e05f852076a8d1160e27c5cd291c_1762764592_84047936/hyprshell.sock
   0.000502107s TRACE hyprland Version { branch: "main", commit: "06b37c390715e05f852076a8d1160e27c5cd291c", version: Some("0.52.0"), dirty: true, commit_message: "protocols/outputMgmt: fix wlr-randr by defering success event until monitor reloads ( 12236)", commit_date: "Sun Nov 9 07:45:53 2025", tag: "v0.52.0-2-g06b37c39", commits: "6561", build_aquamarine: "0.9.4", flags: [] }
   0.000577052s  INFO Starting hyprshell 4.8.0 in release mode on hyprland 0.52.0
   0.000627344s TRACE Found config file at "/home/zosy/.config/hyprshell/config.ron"

(process:5023): Gtk-WARNING **: 16:52:17.876: Unknown key ; gtk-cursor-theme-size in /home/zosy/.config/gtk-4.0/settings.ini
   0.093612694s  INFO preactivate: Using theme: Some("Adwaita") and icon theme: Some("Adwaita"), please make sure both exist, else weird icon or graphical issues may occur
   0.098006126s TRACE preactivate: Icon theme search path: ["/home/zosy/.local/share/icons", "/home/zosy/.icons", "/home/zosy/.local/share/flatpak/exports/share/icons", "/var/lib/flatpak/exports/share/icons", "/usr/share/icons", "/usr/share/pixmaps"]
   0.098029650s DEBUG preactivate:reload_icons: found 314 icons from theme
   0.098307369s DEBUG preactivate:reload_icons: found 0 icons from filesystem in "/home/zosy/.local/share/icons" paths (in background)
   0.098538034s TRACE preactivate:reload_icons: icon map filled
   0.098846263s DEBUG preactivate:reload_icons: found 26 icons from filesystem in "/usr/share/pixmaps" paths (in background)
   0.099147312s DEBUG preactivate:reload_icons: found 1 icons from filesystem in "/var/lib/flatpak/exports/share/icons" paths (in background)
   0.099247583s DEBUG preactivate:reload_icons: found 8 icons from filesystem in "/home/zosy/.local/share/flatpak/exports/share/icons" paths (in background)
   0.099342539s TRACE preactivate:reload_files: found 111 desktop files
   0.101753368s TRACE preactivate:reload_files: Collected all desktop files
   0.102374963s TRACE preactivate:reload_files: found 4 mimeapps lists
   0.102803665s TRACE preactivate:reload_files: Collected all mime files
   0.103044020s TRACE preactivate:reload_class_to_icon_map: filled class to icon map
   0.103228376s TRACE preactivate:reload_desktop_entries_map: filled launcher desktop file map
   0.103236354s DEBUG preactivate: Reloaded desktop data in 4.645241ms
   0.103242653s DEBUG Reloading hyprland config
   0.108445063s DEBUG preactivate:reload_icons: found 1441 icons from filesystem in "/home/zosy/.icons" paths (in background)
   0.249647205s  INFO Starting gui loop
   0.249780796s  INFO socket_handler: Starting socket on "/run/user/1000/hypr/06b37c390715e05f852076a8d1160e27c5cd291c_1762764592_84047936/hyprshell.sock"
   0.249853544s DEBUG Application created
   0.257320499s DEBUG activate: Loading custom css file "/home/zosy/.config/hyprshell/styles.css"
   0.276314756s TRACE activate: Storing previous follow_mouse value: 1
   0.276377845s TRACE activate: Cached version: Version { major: 4, minor: 8, patch: 0 }, current version: Version { major: 4, minor: 8, patch: 0 }: Equal
   0.276561076s DEBUG activate: Hyprshell is up to date
   0.276663118s TRACE activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: No migration needed
   0.276704131s DEBUG activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: Loaded config
   0.276780495s TRACE activate:create_binds:load_plugin: plugins: [Plugin { name: "hyprexpo", author: "Vaxry", handle: "5649c0027ac0", version: "1.0", description: "A plugin for an overview" }, Plugin { name: "hyprwinwrap", author: "Vaxry", handle: "5649bfbe7f30", version: "1.0", description: "A clone of xwinwrap for Hyprland" }]
   0.276843283s TRACE activate:create_binds:load_plugin:generate: extracting plugin from zip
   0.278481312s TRACE activate:create_binds:load_plugin:generate: extracted 5 files
   0.278495153s TRACE activate:create_binds:load_plugin:generate: configuring defs file
   0.278612338s TRACE activate:create_binds:load_plugin:generate: building plugin
   0.278623368s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpso7UhMhyprshell-hyprland-plugin"}: PATH: Some("/usr/share/Modules/bin:/home/zosy/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/zosy/.android-studio/Android/Sdk/platform-tools/:/home/zosy/.local/bin/:/home/zosy/.cargo/bin:/opt/bin:/sbin:/opt/wine/bin")
   0.278634972s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpso7UhMhyprshell-hyprland-plugin"}: CPATH: None
   0.278642493s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpso7UhMhyprshell-hyprland-plugin"}: Running build command: cd "/tmp/.tmpso7UhMhyprshell-hyprland-plugin" && "gcc" "-shared" "-fPIC" "--no-gnu-unique" "-std=c++2b" "-I/usr/include/pixman-1" "-O2" "-o" "/tmp/hyprshell.so" "all.cpp"
   0.298512208s DEBUG preactivate:reload_icons: found 7746 icons from filesystem in "/usr/share/icons" paths (in background)
   4.672640389s TRACE activate:create_binds:load_plugin: generated plugin at "/tmp/hyprshell.so"
   4.673083689s TRACE activate:create_binds:load_plugin: loaded plugin
   4.832853745s TRACE activate:create_binds: layerrules applied
   4.832864947s DEBUG activate: Windows overview disabled
   5.271567689s DEBUG activate:create_windows_switch_window: Created switch window (1)
   5.271747209s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   5.522206533s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   5.772578919s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   6.023027762s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   6.273440381s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   6.523749031s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   6.773987434s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   7.024432691s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   7.274748719s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   7.525043664s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   7.775409189s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   8.025873604s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   8.276244279s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   8.526538411s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   8.776975766s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   9.027304289s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   9.277622622s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   9.527993976s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
   9.778452130s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
  10.028850117s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
  10.279326004s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
  10.529696913s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace

Caused by:
    expected value at line 1 column 1
  10.780098546s ERROR activate: Failed to create windows: failed to create switch window

Caused by:
    0: unable to get initial active data
    1: unable to get initial workspace
    2: expected value at line 1 column 1
  10.780422275s DEBUG activate: Starting hyprshell config reload blocker
  49.378545795s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  49.902504810s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  50.313486595s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
  50.572449441s DEBUG socket_handler:handle_client: Received command: CloseSwitch
 104.880858057s DEBUG socket_handler:handle_client: Received command: CloseSwitch```

**Comment by xskj4** [comment]
patch for 4.8.0
```diff --git a/crates/windows-lib/src/switch/create.rs b/crates/windows-lib/src/switch/create.rs
index e69de29..0000000 100644
--- a/crates/windows-lib/src/switch/create.rs
+++ b/crates/windows-lib/src/switch/create.rs
@@
     clients: HashMap::default(),
-    active: get_initial_active().context("unable to get initial active data")?,
+    active: {
+        // Retry until we can obtain the initial active data. Sometimes hyprland
+        // isn't ready immediately during startup, so loop and sleep briefly.
+        loop {
+            match get_initial_active() {
+                Ok(active) => break active,
+                Err(_) => {
+                    std::thread::sleep(std::time::Duration::from_millis(20));
+                }
+            }
+        }
+    },
     hypr_data: HyprlandData::default(),
 }```

**Comment by H3rmt** [comment]
> 4.8.0 didn’t fix this issue — instead, after logging in, it now takes about 5 seconds for Hyprshell to start working. Please consider my patch; I’ve found that sometimes the “workspace 6” problem isn’t actually caused by Hyprshell, It’s possible that this is actually a Hyprland bug. so my patch completely solves this issue. i used it over weeks, works fine. 4.8.0 log
> 
> ```
>    0.000022118s DEBUG FEATURES: json5_config: true, generate_config_command: true, debug_command: true, launcher_calc: true, clipboard_compress_lz4: true, clipboard_compress_zstd: true, clipboard_compress_brotli: true, clipboard_encrypt_chacha20poly1305: true, clipboard_encrypt_aes_gcm: true
>    0.000048550s DEBUG ENV: HYPRSHELL_NO_LISTENERS: -None-, HYPRSHELL_NO_ALL_ICONS: -None-, HYPRSHELL_RELOAD_TIMEOUT: -None-, HYPRSHELL_LOG_MODULE_PATH: -None-, HYPRSHELL_NO_USE_PLUGIN: -None-, HYPRSHELL_EXPERIMENTAL: -None-, HYPRSHELL_RUN_ACTIONS_IN_DEBUG: -None-
>    0.000073607s DEBUG OS: linux, ARCH: x86_64, NAME="Rocky Linux"
>    0.000111045s DEBUG Checking if daemon is running on /run/user/1000/hypr/06b37c390715e05f852076a8d1160e27c5cd291c_1762764592_84047936/hyprshell.sock
>    0.000502107s TRACE hyprland Version { branch: "main", commit: "06b37c390715e05f852076a8d1160e27c5cd291c", version: Some("0.52.0"), dirty: true, commit_message: "protocols/outputMgmt: fix wlr-randr by defering success event until monitor reloads ( 12236)", commit_date: "Sun Nov 9 07:45:53 2025", tag: "v0.52.0-2-g06b37c39", commits: "6561", build_aquamarine: "0.9.4", flags: [] }
>    0.000577052s  INFO Starting hyprshell 4.8.0 in release mode on hyprland 0.52.0
>    0.000627344s TRACE Found config file at "/home/zosy/.config/hyprshell/config.ron"
> 
> (process:5023): Gtk-WARNING **: 16:52:17.876: Unknown key ; gtk-cursor-theme-size in /home/zosy/.config/gtk-4.0/settings.ini
>    0.093612694s  INFO preactivate: Using theme: Some("Adwaita") and icon theme: Some("Adwaita"), please make sure both exist, else weird icon or graphical issues may occur
>    0.098006126s TRACE preactivate: Icon theme search path: ["/home/zosy/.local/share/icons", "/home/zosy/.icons", "/home/zosy/.local/share/flatpak/exports/share/icons", "/var/lib/flatpak/exports/share/icons", "/usr/share/icons", "/usr/share/pixmaps"]
>    0.098029650s DEBUG preactivate:reload_icons: found 314 icons from theme
>    0.098307369s DEBUG preactivate:reload_icons: found 0 icons from filesystem in "/home/zosy/.local/share/icons" paths (in background)
>    0.098538034s TRACE preactivate:reload_icons: icon map filled
>    0.098846263s DEBUG preactivate:reload_icons: found 26 icons from filesystem in "/usr/share/pixmaps" paths (in background)
>    0.099147312s DEBUG preactivate:reload_icons: found 1 icons from filesystem in "/var/lib/flatpak/exports/share/icons" paths (in background)
>    0.099247583s DEBUG preactivate:reload_icons: found 8 icons from filesystem in "/home/zosy/.local/share/flatpak/exports/share/icons" paths (in background)
>    0.099342539s TRACE preactivate:reload_files: found 111 desktop files
>    0.101753368s TRACE preactivate:reload_files: Collected all desktop files
>    0.102374963s TRACE preactivate:reload_files: found 4 mimeapps lists
>    0.102803665s TRACE preactivate:reload_files: Collected all mime files
>    0.103044020s TRACE preactivate:reload_class_to_icon_map: filled class to icon map
>    0.103228376s TRACE preactivate:reload_desktop_entries_map: filled launcher desktop file map
>    0.103236354s DEBUG preactivate: Reloaded desktop data in 4.645241ms
>    0.103242653s DEBUG Reloading hyprland config
>    0.108445063s DEBUG preactivate:reload_icons: found 1441 icons from filesystem in "/home/zosy/.icons" paths (in background)
>    0.249647205s  INFO Starting gui loop
>    0.249780796s  INFO socket_handler: Starting socket on "/run/user/1000/hypr/06b37c390715e05f852076a8d1160e27c5cd291c_1762764592_84047936/hyprshell.sock"
>    0.249853544s DEBUG Application created
>    0.257320499s DEBUG activate: Loading custom css file "/home/zosy/.config/hyprshell/styles.css"
>    0.276314756s TRACE activate: Storing previous follow_mouse value: 1
>    0.276377845s TRACE activate: Cached version: Version { major: 4, minor: 8, patch: 0 }, current version: Version { major: 4, minor: 8, patch: 0 }: Equal
>    0.276561076s DEBUG activate: Hyprshell is up to date
>    0.276663118s TRACE activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: No migration needed
>    0.276704131s DEBUG activate:load_config{path="/home/zosy/.config/hyprshell/config.ron"}: Loaded config
>    0.276780495s TRACE activate:create_binds:load_plugin: plugins: [Plugin { name: "hyprexpo", author: "Vaxry", handle: "5649c0027ac0", version: "1.0", description: "A plugin for an overview" }, Plugin { name: "hyprwinwrap", author: "Vaxry", handle: "5649bfbe7f30", version: "1.0", description: "A clone of xwinwrap for Hyprland" }]
>    0.276843283s TRACE activate:create_binds:load_plugin:generate: extracting plugin from zip
>    0.278481312s TRACE activate:create_binds:load_plugin:generate: extracted 5 files
>    0.278495153s TRACE activate:create_binds:load_plugin:generate: configuring defs file
>    0.278612338s TRACE activate:create_binds:load_plugin:generate: building plugin
>    0.278623368s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpso7UhMhyprshell-hyprland-plugin"}: PATH: Some("/usr/share/Modules/bin:/home/zosy/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/zosy/.android-studio/Android/Sdk/platform-tools/:/home/zosy/.local/bin/:/home/zosy/.cargo/bin:/opt/bin:/sbin:/opt/wine/bin")
>    0.278634972s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpso7UhMhyprshell-hyprland-plugin"}: CPATH: None
>    0.278642493s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpso7UhMhyprshell-hyprland-plugin"}: Running build command: cd "/tmp/.tmpso7UhMhyprshell-hyprland-plugin" && "gcc" "-shared" "-fPIC" "--no-gnu-unique" "-std=c++2b" "-I/usr/include/pixman-1" "-O2" "-o" "/tmp/hyprshell.so" "all.cpp"
>    0.298512208s DEBUG preactivate:reload_icons: found 7746 icons from filesystem in "/usr/share/icons" paths (in background)
>    4.672640389s TRACE activate:create_binds:load_plugin: generated plugin at "/tmp/hyprshell.so"
>    4.673083689s TRACE activate:create_binds:load_plugin: loaded plugin
>    4.832853745s TRACE activate:create_binds: layerrules applied
>    4.832864947s DEBUG activate: Windows overview disabled
>    5.271567689s DEBUG activate:create_windows_switch_window: Created switch window (1)
>    5.271747209s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    5.522206533s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    5.772578919s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    6.023027762s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    6.273440381s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    6.523749031s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    6.773987434s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    7.024432691s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    7.274748719s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    7.525043664s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    7.775409189s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    8.025873604s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    8.276244279s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    8.526538411s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    8.776975766s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    9.027304289s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    9.277622622s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    9.527993976s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>    9.778452130s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>   10.028850117s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>   10.279326004s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>   10.529696913s  WARN activate:create_windows_switch_window: waiting for correct initial active state: unable to get initial workspace
> 
> Caused by:
>     expected value at line 1 column 1
>   10.780098546s ERROR activate: Failed to create windows: failed to create switch window
> 
> Caused by:
>     0: unable to get initial active data
>     1: unable to get initial workspace
>     2: expected value at line 1 column 1
>   10.780422275s DEBUG activate: Starting hyprshell config reload blocker
>   49.378545795s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
>   49.902504810s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
>   50.313486595s DEBUG socket_handler:handle_client: Received command: OpenSwitch(OpenSwitch { reverse: false })
>   50.572449441s DEBUG socket_handler:handle_client: Received command: CloseSwitch
>  104.880858057s DEBUG socket_handler:handle_client: Received command: CloseSwitch```
> ```

looks like the 5 seoconds werent enough, increased to 20 for the next version

**Comment by H3rmt** [comment]
> patch for 4.8.0
> 
> index e69de29..0000000 100644
> --- a/crates/windows-lib/src/switch/create.rs
> +++ b/crates/windows-lib/src/switch/create.rs
> @@
>      clients: HashMap::default(),
> -    active: get_initial_active().context("unable to get initial active data")?,
> +    active: {
> +        // Retry until we can obtain the initial active data. Sometimes hyprland
> +        // isn't ready immediately during startup, so loop and sleep briefly.
> +        loop {
> +            match get_initial_active() {
> +                Ok(active) => break active,
> +                Err(_) => {
> +                    std::thread::sleep(std::time::Duration::from_millis(20));
> +                }
> +            }
> +        }
> +    },
>      hypr_data: HyprlandData::default(),
>  }```

This was added in `4.8.0`

```rs
pub fn get_initial_active() -> anyhow::Result<Active> {
    let mut tries = 0;
    loop {
        match internal_get_initial_active() {
            Ok(a) => break Ok(a),
            Err(e) => {
                warn!("waiting for correct initial active state: {e:?}");
                thread::sleep(Duration::from_millis(500));
            }
        }
        if tries > 40 {
            break internal_get_initial_active();
        }
        tries += 1;
    }
}
```

**Comment by H3rmt** [comment]
increased to 20 seconds in `v4.8.1`
